# Generated by Django 5.0.2 on 2024-02-19 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aircrafts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aircraft',
            old_name='name',
            new_name='aircraft_name',
        ),
    ]
