# Generated by Django 5.0.2 on 2024-02-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircrafts', '0002_rename_name_aircraft_aircraft_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='iata_code',
            field=models.CharField(verbose_name='ИАТА код авиакомпании'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='icao_code',
            field=models.CharField(verbose_name='ИКАО код авиакомпании'),
        ),
    ]
