# Generated by Django 5.0.2 on 2024-02-21 13:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aircrafts', '0003_alter_aircraft_iata_code_alter_aircraft_icao_code'),
        ('airlines', '0002_airline_delete_airlines'),
        ('airports', '0003_rename_airports_airport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Уникальный идентификатор объекта')),
                ('flight_number', models.CharField(verbose_name='Номер рейса')),
                ('start_date', models.DateField(verbose_name='Дата начала действия рейса')),
                ('end_date', models.DateField(verbose_name='Дата окончания действия рейса')),
                ('time', models.TimeField(verbose_name='Время начала вполнения рейса')),
                ('duration', models.TimeField(verbose_name='Продолжительность полета')),
                ('extra_info', models.TextField(null=True, verbose_name='Дополнительная информация в свободной форме')),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='aircrafts.aircraft', verbose_name='Идентификатор самолета')),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='airlines.airline', verbose_name='Идентификатор авиакомпании')),
                ('mar_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mar_1_flights', to='airports.airport', verbose_name='Идентификатор аэропорта вылета')),
                ('mar_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nar_2_flights', to='airports.airport', verbose_name='Идентификатор аэропорта прилета')),
            ],
        ),
    ]
