# Generated by Django 5.0.2 on 2024-02-21 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0003_rename_airports_airport'),
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flights',
            name='mar_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mar_2_flights', to='airports.airport', verbose_name='Идентификатор аэропорта прилета'),
        ),
    ]
