# Generated by Django 5.0.2 on 2024-02-21 13:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Уникальный идентификатор объекта')),
                ('icao_code', models.CharField(verbose_name='ИКАО код авиакомпании')),
                ('iata_code', models.CharField(verbose_name='ИАТА код авиакомпании')),
                ('extra_info', models.TextField(null=True, verbose_name='Дополнительная информация в свободной форме')),
                ('airline_name', models.CharField(verbose_name='Название авиакомпании')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Airlines',
        ),
    ]
