# Generated by Django 5.0.2 on 2024-02-21 12:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airports',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Уникальный идентификатор объекта')),
                ('icao_code', models.CharField(verbose_name='ИКАО код авиакомпании')),
                ('iata_code', models.CharField(verbose_name='ИАТА код авиакомпании')),
                ('extra_info', models.TextField(null=True, verbose_name='Дополнительная информация в свободной форме')),
                ('airport_name', models.CharField(verbose_name='Названиеавие аэропорта')),
                ('latitude', models.FloatField(verbose_name='Широта')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
