# Generated by Django 5.0.2 on 2024-02-21 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0002_airports_altitude_airports_longitude'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Airports',
            new_name='Airport',
        ),
    ]
